spin_manifest_version = 2

[application]
name = "spin-kv-counter-go"
version = "0.1.0"
authors = ["Rajat Jindal <rajatjindal83@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "spin-kv-counter-go"

[component.spin-kv-counter-go]
source = "main.wasm"
allowed_outbound_hosts = []
key_value_stores = ["default"]
[component.spin-kv-counter-go.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
